---
- name: Install Specific versions of packages using Chocolatey
  hosts: all
  gather_facts: false
  tasks:

  - name: Install specific versions of packages sequentially
    win_chocolatey:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
    loop: "{{ choco_packages }}"


