---
- name: Specific versions of packages using Chocolatey
  hosts: all
  gather_facts: false
  tasks:

  - name: Modify choco packages
    win_chocolatey:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: "{{ item.state| default ('present') }}"
    loop: "{{ choco_packages }}"
